# Generated by Django 2.2.24 on 2021-08-05 10:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('remplissages', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivie',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suivis', to=settings.AUTH_USER_MODEL, verbose_name='ajouter par '),
        ),
        migrations.AlterField(
            model_name='person',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author_personnes', to=settings.AUTH_USER_MODEL, verbose_name='ajouter par '),
        ),
    ]
