# Generated by Django 2.2.24 on 2021-08-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplissages', '0002_auto_20210805_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='description',
            field=models.TextField(blank=True, help_text='ajouter une description du site', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, help_text='ajouter une photo', null=True, upload_to='images/profile/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone',
            field=models.PositiveIntegerField(blank=True, default=0, help_text='le numéro de télephone doit avpir 9 chiffres', null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='image',
            field=models.ImageField(blank=True, help_text='ajouter une image', null=True, upload_to='images/site/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='site',
            name='nom_site_evangelisation',
            field=models.CharField(help_text='le nom du site doit avoir au moins 03 caractères', max_length=200, verbose_name="site d'évangélisation"),
        ),
    ]
