# Generated by Django 2.2.24 on 2021-08-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplissages', '0004_auto_20210806_2127'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='actif',
            field=models.CharField(choices=[('oui', 'Oui'), ('non', 'Non')], default='non', max_length=15),
        ),
    ]
