# Generated by Django 2.2.24 on 2021-08-07 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplissages', '0006_auto_20210807_0603'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='contacts',
            field=models.PositiveIntegerField(),
        ),
    ]
