# Generated by Django 2.2.24 on 2021-08-07 06:47

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplissages', '0007_auto_20210807_0609'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='boss',
            field=models.ManyToManyField(help_text='selectionner les boss qui ont évangelisés cette personne', related_name='personnes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='nom_et_prenom',
            field=models.CharField(help_text='ce champ doit avoir au moins trois caractères', max_length=200, verbose_name='Nom et Prénom'),
        ),
        migrations.AlterField(
            model_name='person',
            name='quartier_d_habitation',
            field=models.CharField(help_text='ce champ doit avoir au moins trois caractères', max_length=200, verbose_name="Quartier d'habitation"),
        ),
        migrations.AlterField(
            model_name='person',
            name='sujets_de_priere',
            field=models.TextField(blank=True, help_text='ce champ est optionnel', null=True, verbose_name='Prière et observation'),
        ),
        migrations.AlterField(
            model_name='person',
            name='temoignages',
            field=models.TextField(blank=True, help_text='ce champ est optionnel', null=True, verbose_name='Témoignage'),
        ),
    ]
