# Generated by Django 2.2.24 on 2021-08-09 09:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('remplissages', '0008_auto_20210807_0647'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='evangelisation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personnes', to='remplissages.Evangelisation', verbose_name="Moment d'évangelisation"),
        ),
    ]
