# Generated by Django 2.2.24 on 2021-08-09 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplissages', '0009_person_evangelisation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='date',
            field=models.DateField(),
        ),
    ]
