# Generated by Django 2.2.24 on 2021-08-09 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplissages', '0010_auto_20210809_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='suivie',
            name='boos_suivi',
            field=models.TextField(default=0, verbose_name='Boss ayant éffectuer le suivi'),
            preserve_default=False,
        ),
    ]
