# Generated by Django 2.2.24 on 2021-08-12 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remplissages', '0011_suivie_boos_suivi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='titre',
            field=models.CharField(max_length=250, verbose_name='Titre'),
        ),
    ]
