# Generated by Django 2.2.24 on 2021-08-11 02:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0003_auto_20210809_0903'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='history',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='history',
            name='object_id',
        ),
        migrations.AddField(
            model_name='history',
            name='content_object',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
